package
{
   public final class CanvasHudTargetCatalog
   {
      private static const TARGETS:Object = {
         "ship.target-components": ["@ship:TargetComponentIndicator"],
         "ship.activator-markers": ["@ship:ActivatorIcon"],
         "ship.star-markers": ["@ship:CelestialIcon"],
         "ship.hailing-markers": ["@ship:HailingIcon"],
         "ship.loot-markers": ["@ship:LootIcon"],
         "ship.poi-markers": ["@ship:POIIcon"],
         "ship.ship-markers": ["@ship:ShipTargetIcon"],
         "ship.station-markers": ["@ship:StationIcon"],
         "ship.planet-markers": ["@ship:PlanetIcon"],
         "ship.destructible-markers": ["@ship:DestructibleObjectIcon"],
         "ship.quest-markers": ["@ship:QuestIcon"],
         "ship.landing-markers": ["@ship:LandingMarkerIndicator"],
         "ship.off-screen-markers": ["@ship:OffScreenIcon"],
         "ship.reticle-buttons": ["Reticle_mc.ShipReticle_mc.ButtonBar_mc"],
         "player.health-label": ["RightMeters_mc.Health_mc"],
         "player.health-track": ["RightMeters_mc.HealthBarEmpty_mc"],
         "player.health-ghost": ["RightMeters_mc.HealthBarGhost_mc"],
         "player.health-damage": ["RightMeters_mc.HealthBarDamage_mc"],
         "player.health-fill": ["RightMeters_mc.HealthBar_mc"],
         "player.health-increase": ["RightMeters_mc.HealthBarIncrease_mc"],
         "player.power-fill": ["RightMeters_mc.PowerBar_mc"],
         "player.power-increase": ["RightMeters_mc.PowerBarIncrease_mc"],
         "player.meter-divider-primary": ["RightMeters_mc.VerticalDivider_mc"],
         "player.meter-divider-secondary": ["RightMeters_mc.VerticalDivider2_mc"],
         "player.vehicle-exit-button": ["RightMeters_mc.HUDVehicle_mc.GetUpButton_mc"],
         "ship.throttle": ["Reticle_mc.ShipReticle_mc.ThrottleComponent_mc"],
         "ship.boost": ["Reticle_mc.ShipReticle_mc.BoostComponent_mc"],
         "ship.heading": ["Reticle_mc.ShipReticle_mc.HeadingIndicator_mc"],
         "ship.lock-on": ["Reticle_mc.ShipReticle_mc.LockOn_mc"],
         "ship.thrusters": ["Reticle_mc.ShipReticle_mc.ThrusterIcon_mc"],
         "ship.speed-label": ["Reticle_mc.ShipReticle_mc.SpeedName_mc"],
         "ship.roll": ["Reticle_mc.ShipReticle_mc.RollIndicator_mc"],
         "ship.lead-circle": ["Reticle_mc.ShipReticle_mc.LeadCircle_mc"],
         "ship.contraband": ["Reticle_mc.ShipReticle_mc.ContrabandWarning_mc"],
         "ship.turn-rate": ["Reticle_mc.ShipReticle_mc.MaxTurnRate_mc"],
         "ship.target-panel": ["Reticle_mc.ShipReticle_mc.TargetPanel_mc"],
         "ship.target-lock": ["Reticle_mc.ShipReticle_mc.TargetLockCircle_mc"],
         "ship.targeting-ap": ["Reticle_mc.ShipReticle_mc.APBar_mc"],
         "ship.engine-alert": ["Reticle_mc.ShipReticle_mc.AlertEng_mc"],
         "ship.grav-alert": ["Reticle_mc.ShipReticle_mc.AlertGrav_mc"],
         "ship.shield-alert": ["Reticle_mc.ShipReticle_mc.AlertShield_mc"],
         "ship.hull-alert": ["Reticle_mc.ShipReticle_mc.AlertHull_mc"],
         "ship.boost-button": ["Reticle_mc.ShipReticle_mc.BoostName_mc"],
         "ship.cruise-button": ["Reticle_mc.ShipReticle_mc.CruiseName_mc"],
         "ship.exit-cruise-button": ["Reticle_mc.ShipReticle_mc.ExitCruiseHolder_mc"],
         "ship.power-dpad": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.DPadButton_mc"],
         "ship.power-increase": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.UpButton_mc"],
         "ship.power-decrease": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.DownButton_mc"],
         "ship.power-count": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.BarCount_mc"],
         "ship.power-free-status": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.FreeLaneStatus_mc"],
         "ship.power-free-title": ["PowerAllocationComponentWrapper_mc.PowerAllocationComponent_mc.FreeLaneTitle_mc"],
         "ship.hull-meter": ["ShieldComponentWrapper_mc.ShieldComponent_mc.INTMeter_mc"],
         "ship.shield-health": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ShieldHealth_mc"],
         "ship.outline": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ShipOutline_mc"],
         "ship.repair-button": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ShipRepairButton_mc"],
         "ship.hull-label": ["ShieldComponentWrapper_mc.ShieldComponent_mc.HullLabel_mc"],
         "ship.repair-animation": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ShipRepairAnim_mc"],
         "ship.grav-power-required": ["GravJumpComponent_mc.GravNeedsPower_mc"],
         "ship.grav-progress": ["GravJumpComponent_mc.GravJumpProgress_mc"],
         "ship.grav-cancel": ["GravJumpComponent_mc.CancelButton_mc"],
         "ship.starborn-grav-power-required": ["StarbornGravJumpComponent_mc.GravNeedsPower_mc"],
         "ship.starborn-grav-progress": ["StarbornGravJumpComponent_mc.GravJumpProgress_mc"],
         "ship.starborn-grav-cancel": ["StarbornGravJumpComponent_mc.CancelButton_mc"],
         "ship.hail-name": ["HailComponent_mc.Name_mc"],
         "ship.hail-buttons": ["HailComponent_mc.ButtonBar_mc"],
         "ship.container-list": ["ShipHudQuickContainer_mc.List_mc"],
         "ship.container-target-name": ["ShipHudQuickContainer_mc.TargetName_tf"],
         "ship.container-player-inventory": ["ShipHudQuickContainer_mc.PlayerInvData_mc"],
         "ship.container-buttons": ["ShipHudQuickContainer_mc.ButtonBar_mc"],
         "ship.container-header": ["ShipHudQuickContainer_mc.Header_mc"],
         "ship.component-status-1": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus1_mc"],
         "ship.component-status-2": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus2_mc"],
         "ship.component-status-3": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus3_mc"],
         "ship.component-status-4": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus4_mc"],
         "ship.component-status-5": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus5_mc"],
         "ship.component-status-6": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus6_mc"],
         "ship.component-status-7": ["ShieldComponentWrapper_mc.ShieldComponent_mc.ComponentStatus7_mc"],
         "canvas.watch":["@watch"],
         "player.center":["CenterGroup_mc"],
         "player.crosshair":["CenterGroup_mc.ReticleBase_mc"],
         "player.power-notification":["CenterGroup_mc.ArtifactPowersWidget_mc"],
         "player.explosive-indicators":["CenterGroup_mc.ExplosiveIndicatorBase_mc"],
         "player.directional-damage":["CenterGroup_mc.DirectionalHitIndicatorBase_mc"],
         "player.hit-damage":["HitDamageBase_mc"],
         "player.hit-and-kill":["HitAndKillIndicator_mc"],
         "player.hit-indicator":["HitAndKillIndicator_mc.HitIndicator_mc"],
         "player.kill-indicator":["HitAndKillIndicator_mc.KillIndicator_mc"],
         "player.top-center":["TopCenterGroup_mc"],
         "player.stealth":["TopCenterGroup_mc.StealthMeter_mc"],
         "player.enemy-health":["EnemyHealthHolder_mc"],
         "player.quest-markers":["FloatingQuestMarkerBase"],
         "player.rollover":["RolloverWidget_mc"],
         "player.rollover-activation":["RolloverWidget_mc.RolloverActivationHolder_mc"],
         "player.rollover-reticle":["RolloverWidget_mc.Reticle_mc"],
         "player.social-commands":["SocialCommandIcons_mc"],
         "player.crew-buffs":["CrewBuffWidget_mc"],
         "player.meters":["RightMeters_mc"],
         "player.health":["RightMeters_mc.Health_mc","RightMeters_mc.HealthBarEmpty_mc","RightMeters_mc.HealthBarGhost_mc","RightMeters_mc.HealthBarDamage_mc","RightMeters_mc.HealthBar_mc","RightMeters_mc.HealthBarIncrease_mc"],
         "player.power":["RightMeters_mc.PowerBar_mc","RightMeters_mc.PowerBarIncrease_mc"],
         "player.jetpack":["RightMeters_mc.JetpackMeterWrapper_mc"],
         "player.weapon-icon":["RightMeters_mc.EquippedWeaponIconHolder_mc"],
         "player.ammo":["RightMeters_mc.EquippedWeaponAmmo_mc"],
         "player.ammo-reserve":["RightMeters_mc.EquippedWeaponAmmoTotal_mc"],
         "player.grenade-icon":["RightMeters_mc.EquippedGrenadeIcon_mc"],
         "player.grenade-count":["RightMeters_mc.EquippedGrenadeCount_mc"],
         "player.meter-dividers":["RightMeters_mc.VerticalDivider_mc","RightMeters_mc.VerticalDivider2_mc"],
         "player.vehicle-exit":["RightMeters_mc.HUDVehicle_mc"],
         "ship.power":["PowerAllocationComponentWrapper_mc"],
         "ship.shields":["ShieldComponentWrapper_mc"],
         "ship.get-up":["GetUpButton_mc"],
         "ship.reticle":["Reticle_mc"],
         "ship.target-indicator":["Reticle_mc.ShipReticle_mc"],
         "ship.body-marker":["Reticle_mc.BodyViewMarker_mc"],
         "ship.indicator-buttons":["Reticle_mc.IndicatorButtonBar_mc"],
         "ship.grav-jump":["GravJumpComponent_mc"],
         "ship.starborn-grav-jump":["StarbornGravJumpComponent_mc"],
         "ship.alerts":["Alerts_mc"],
         "ship.quick-container":["ShipHudQuickContainer_mc"],
         "ship.hail":["HailComponent_mc"],
         "ship.buttons":["ButtonBar_mc"],
         "ship.scan":["ScanDetails_mc"],
         "ship.scan-ship":["ScanDetails_mc.Internal_mc.ShipInfo_mc"],
         "ship.scan-planet":["ScanDetails_mc.Internal_mc.PlanetInfo_mc"],
         "ship.debug-text":["DebugText_tf"],
         "ship.debug-buttons":["DebugButtonHints_tf"]
      };

      public static function dynamicClass(name:String) : Boolean { return ["TargetComponentIndicator","ActivatorIcon","CelestialIcon","HailingIcon","LootIcon","POIIcon","ShipTargetIcon","StationIcon","PlanetIcon","DestructibleObjectIcon","QuestIcon","LandingMarkerIndicator","OffScreenIcon"].indexOf(name) >= 0; }

      public static function resolve(target:String, host:String) : Array
      {
         if(target == "canvas.watch") return host == "player" ? ["@watch"] : null;
         if(target == "player.all" || target == "ship.all")
         {
            if(target != host+".all") return null;
            var paths:Array = [];
            for(var name:String in TARGETS)
               if(name.indexOf(host+".") == 0)
                  for each(var path:String in TARGETS[name]) if(paths.indexOf(path) < 0) paths.push(path);
            return paths;
         }
         return target.indexOf(host+".") == 0 && TARGETS.hasOwnProperty(target) ? (TARGETS[target] as Array).concat() : null;
      }
   }
}
